-- Run with SQLcl/SQL*Plus on a backed-up develop schema before deploying the application.
-- DDL commits implicitly. Existing rows keep SCHEMA_VERSION=1; USE_YN is preserved.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
DECLARE duplicate_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO duplicate_count FROM (SELECT DET_RULE_TYPE FROM DETECTION_RULES GROUP BY DET_RULE_TYPE HAVING COUNT(*) > 1);
    IF duplicate_count > 0 THEN RAISE_APPLICATION_ERROR(-20010, 'Resolve duplicate rule codes before migration'); END IF;
END;
/
DECLARE
    column_count NUMBER;
    PROCEDURE add_column(table_name_in VARCHAR2, column_name_in VARCHAR2, definition_in VARCHAR2) IS
    BEGIN
        SELECT COUNT(*) INTO column_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = table_name_in AND COLUMN_NAME = column_name_in;
        IF column_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE ' || table_name_in || ' ADD (' || column_name_in || ' ' || definition_in || ')'; END IF;
    END;
BEGIN
    add_column('INSPECTIONS', 'SCHEMA_VERSION', 'NUMBER DEFAULT 1 NOT NULL');
    add_column('INSPECTIONS', 'PARSED_RECORD_COUNT', 'NUMBER DEFAULT 0 NOT NULL');
    add_column('INSPECTIONS', 'UNPARSED_LINE_COUNT', 'NUMBER DEFAULT 0 NOT NULL');
    add_column('INSPECTIONS', 'PARSE_FAILURE_COUNT', 'NUMBER DEFAULT 0 NOT NULL');
    add_column('INSPECTIONS', 'CHANGE_COUNT', 'NUMBER DEFAULT 0 NOT NULL');
    add_column('INSPECTIONS', 'UNKNOWN_COUNT', 'NUMBER DEFAULT 0 NOT NULL');
    add_column('INSPECTIONS', 'FAILED_OPERATION_COUNT', 'NUMBER DEFAULT 0 NOT NULL');
    add_column('INSPECTIONS', 'RULE_SNAPSHOT', 'CLOB');
    add_column('DETECTION_RESULTS', 'LINE_END', 'NUMBER');
    add_column('DETECTION_RESULTS', 'CATEGORY', 'VARCHAR2(30)');
    add_column('DETECTION_RESULTS', 'RESULT_SEVERITY', 'VARCHAR2(10)');
    add_column('DETECTION_RESULTS', 'FINDING_TYPE', 'VARCHAR2(30)');
    add_column('DETECTION_RESULTS', 'OPERATION_ID', 'VARCHAR2(100)');
    add_column('DETECTION_RESULTS', 'OPERATION_TYPE', 'VARCHAR2(40)');
    add_column('DETECTION_RESULTS', 'BUSINESS_DATE', 'VARCHAR2(20)');
    add_column('DETECTION_RESULTS', 'TRANSACTION_KEY', 'VARCHAR2(100)');
    add_column('DETECTION_RESULTS', 'REASON_CODE', 'VARCHAR2(500)');
    add_column('DETECTION_RESULTS', 'PREVIOUS_LINE_NO', 'NUMBER');
    add_column('DETECTION_RESULTS', 'PREVIOUS_LOG_CONTENT', 'CLOB');
    add_column('DETECTION_RESULTS', 'PREVIOUS_VALUE', 'CLOB');
    add_column('DETECTION_RESULTS', 'CURRENT_VALUE', 'CLOB');
    add_column('DETECTION_RESULTS', 'EVENT_TIME', 'VARCHAR2(40)');
END;
/
DECLARE table_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_count FROM USER_TABLES WHERE TABLE_NAME = 'ANALYSIS_OPERATIONS';
    IF table_count = 0 THEN EXECUTE IMMEDIATE q'[CREATE TABLE ANALYSIS_OPERATIONS (
    INS_NO NUMBER NOT NULL, OPERATION_ID VARCHAR2(100) NOT NULL,
    CATEGORY VARCHAR2(30) NOT NULL, OPERATION_TYPE VARCHAR2(40) NOT NULL,
    DEVICE_ID VARCHAR2(100), BUSINESS_DATE VARCHAR2(20), TRANSACTION_KEY VARCHAR2(100),
    RESULT_STATUS VARCHAR2(20) NOT NULL, REASON_CODE VARCHAR2(500),
    LINE_NO NUMBER NOT NULL, LINE_END NUMBER NOT NULL, LOG_CONTENT CLOB,
    CONSTRAINT PK_ANALYSIS_OPERATIONS PRIMARY KEY (INS_NO, OPERATION_ID),
    CONSTRAINT FK_OPERATIONS_INSPECTION FOREIGN KEY (INS_NO) REFERENCES INSPECTIONS(INS_NO),
    CONSTRAINT CK_OPERATIONS_STATUS CHECK (RESULT_STATUS IN ('SUCCESS', 'ERROR', 'UNKNOWN')),
    CONSTRAINT CK_OPERATIONS_LINES CHECK (LINE_NO > 0 AND LINE_END >= LINE_NO)
)]'; END IF;
END;
/
DECLARE n NUMBER; BEGIN SELECT COUNT(*) INTO n FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'CK_LOG_FILES_SOURCE'; IF n > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE LOG_FILES DROP CONSTRAINT CK_LOG_FILES_SOURCE'; END IF; END;
/
ALTER TABLE LOG_FILES ADD CONSTRAINT CK_LOG_FILES_SOURCE CHECK (SOURCE_TYPE IN ('VENDING','PAYMENT','UNKNOWN','DEVICE_STATUS','EXTERNAL_RETRANSMISSION','EXTERNAL_INTEGRATION','MIXED'));
DECLARE n NUMBER; BEGIN SELECT COUNT(*) INTO n FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'CK_RESULTS_STATUS'; IF n > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE DETECTION_RESULTS DROP CONSTRAINT CK_RESULTS_STATUS'; END IF; END;
/
ALTER TABLE DETECTION_RESULTS ADD CONSTRAINT CK_RESULTS_STATUS CHECK (RESULT_STATUS IN ('SUCCESS','ERROR','CHANGE','UNKNOWN'));
DECLARE n NUMBER; BEGIN SELECT COUNT(*) INTO n FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'UK_RULE_TYPE'; IF n = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE DETECTION_RULES ADD CONSTRAINT UK_RULE_TYPE UNIQUE (DET_RULE_TYPE)'; END IF; END;
/
MERGE INTO DETECTION_RULES D USING (SELECT 'MISSING_PRODUCT_NAME' RULE_TYPE FROM DUAL) S
ON (D.DET_RULE_TYPE = S.RULE_TYPE)
WHEN MATCHED THEN UPDATE SET D.DET_PATTERN = 'EMPTY_PRODUCT_NAME', D.DET_DESCRIPTION = '상품명 누락', D.LOG_TYPE = 'DEVICE_STATUS', D.SEVERITY = 'WARN'
WHEN NOT MATCHED THEN INSERT (DET_NO, DET_RULE_TYPE, DET_PATTERN, DET_DESCRIPTION, LOG_TYPE, SEVERITY, USE_YN, REG_DATE)
VALUES (SEQ_DETECTION_RULES.NEXTVAL, S.RULE_TYPE, 'EMPTY_PRODUCT_NAME', '상품명 누락', 'DEVICE_STATUS', 'WARN', 'Y', SYSDATE);
MERGE INTO DETECTION_RULES D USING (SELECT 'CORRUPTED_DATA' RULE_TYPE FROM DUAL) S
ON (D.DET_RULE_TYPE = S.RULE_TYPE)
WHEN MATCHED THEN UPDATE SET D.DET_PATTERN = 'INVALID_CHARACTER', D.DET_DESCRIPTION = '비정상 문자', D.LOG_TYPE = 'DEVICE_STATUS', D.SEVERITY = 'WARN'
WHEN NOT MATCHED THEN INSERT (DET_NO, DET_RULE_TYPE, DET_PATTERN, DET_DESCRIPTION, LOG_TYPE, SEVERITY, USE_YN, REG_DATE)
VALUES (SEQ_DETECTION_RULES.NEXTVAL, S.RULE_TYPE, 'INVALID_CHARACTER', '비정상 문자', 'DEVICE_STATUS', 'WARN', 'Y', SYSDATE);
MERGE INTO DETECTION_RULES D USING (SELECT 'MISSING_SLOT' RULE_TYPE FROM DUAL) S
ON (D.DET_RULE_TYPE = S.RULE_TYPE)
WHEN MATCHED THEN UPDATE SET D.DET_PATTERN = 'PREVIOUS_SLOT_COMPARE', D.DET_DESCRIPTION = '슬롯 누락 후보', D.LOG_TYPE = 'DEVICE_STATUS', D.SEVERITY = 'WARN'
WHEN NOT MATCHED THEN INSERT (DET_NO, DET_RULE_TYPE, DET_PATTERN, DET_DESCRIPTION, LOG_TYPE, SEVERITY, USE_YN, REG_DATE)
VALUES (SEQ_DETECTION_RULES.NEXTVAL, S.RULE_TYPE, 'PREVIOUS_SLOT_COMPARE', '슬롯 누락 후보', 'DEVICE_STATUS', 'WARN', 'Y', SYSDATE);
MERGE INTO DETECTION_RULES D USING (SELECT 'PRICE_CHANGED' RULE_TYPE FROM DUAL) S
ON (D.DET_RULE_TYPE = S.RULE_TYPE)
WHEN MATCHED THEN UPDATE SET D.DET_PATTERN = 'PREVIOUS_PRICE_COMPARE', D.DET_DESCRIPTION = '가격 변경', D.LOG_TYPE = 'DEVICE_STATUS', D.SEVERITY = 'INFO'
WHEN NOT MATCHED THEN INSERT (DET_NO, DET_RULE_TYPE, DET_PATTERN, DET_DESCRIPTION, LOG_TYPE, SEVERITY, USE_YN, REG_DATE)
VALUES (SEQ_DETECTION_RULES.NEXTVAL, S.RULE_TYPE, 'PREVIOUS_PRICE_COMPARE', '가격 변경', 'DEVICE_STATUS', 'INFO', 'Y', SYSDATE);
MERGE INTO DETECTION_RULES D USING (SELECT 'PRODUCT_NAME_CHANGED' RULE_TYPE FROM DUAL) S
ON (D.DET_RULE_TYPE = S.RULE_TYPE)
WHEN MATCHED THEN UPDATE SET D.DET_PATTERN = 'PREVIOUS_NAME_COMPARE', D.DET_DESCRIPTION = '상품명 변경', D.LOG_TYPE = 'DEVICE_STATUS', D.SEVERITY = 'INFO'
WHEN NOT MATCHED THEN INSERT (DET_NO, DET_RULE_TYPE, DET_PATTERN, DET_DESCRIPTION, LOG_TYPE, SEVERITY, USE_YN, REG_DATE)
VALUES (SEQ_DETECTION_RULES.NEXTVAL, S.RULE_TYPE, 'PREVIOUS_NAME_COMPARE', '상품명 변경', 'DEVICE_STATUS', 'INFO', 'Y', SYSDATE);
MERGE INTO DETECTION_RULES D USING (SELECT 'STOCK_CHANGED' RULE_TYPE FROM DUAL) S
ON (D.DET_RULE_TYPE = S.RULE_TYPE)
WHEN MATCHED THEN UPDATE SET D.DET_PATTERN = 'PREVIOUS_STOCK_COMPARE', D.DET_DESCRIPTION = '재고 변화', D.LOG_TYPE = 'DEVICE_STATUS', D.SEVERITY = 'INFO'
WHEN NOT MATCHED THEN INSERT (DET_NO, DET_RULE_TYPE, DET_PATTERN, DET_DESCRIPTION, LOG_TYPE, SEVERITY, USE_YN, REG_DATE)
VALUES (SEQ_DETECTION_RULES.NEXTVAL, S.RULE_TYPE, 'PREVIOUS_STOCK_COMPARE', '재고 변화', 'DEVICE_STATUS', 'INFO', 'Y', SYSDATE);
MERGE INTO DETECTION_RULES D USING (SELECT 'SLOT_RESTORED' RULE_TYPE FROM DUAL) S
ON (D.DET_RULE_TYPE = S.RULE_TYPE)
WHEN MATCHED THEN UPDATE SET D.DET_PATTERN = 'PREVIOUS_MISSING_SLOT', D.DET_DESCRIPTION = '슬롯 재등장', D.LOG_TYPE = 'DEVICE_STATUS', D.SEVERITY = 'INFO'
WHEN NOT MATCHED THEN INSERT (DET_NO, DET_RULE_TYPE, DET_PATTERN, DET_DESCRIPTION, LOG_TYPE, SEVERITY, USE_YN, REG_DATE)
VALUES (SEQ_DETECTION_RULES.NEXTVAL, S.RULE_TYPE, 'PREVIOUS_MISSING_SLOT', '슬롯 재등장', 'DEVICE_STATUS', 'INFO', 'Y', SYSDATE);
MERGE INTO DETECTION_RULES D USING (SELECT 'DB_TRANSFER_SUCCESS' RULE_TYPE FROM DUAL) S
ON (D.DET_RULE_TYPE = S.RULE_TYPE)
WHEN MATCHED THEN UPDATE SET D.DET_PATTERN = 'EXPLICIT_SQL_SUCCESS', D.DET_DESCRIPTION = '외부 시스템 재전송 성공', D.LOG_TYPE = 'EXTERNAL_INTEGRATION', D.SEVERITY = 'INFO'
WHEN NOT MATCHED THEN INSERT (DET_NO, DET_RULE_TYPE, DET_PATTERN, DET_DESCRIPTION, LOG_TYPE, SEVERITY, USE_YN, REG_DATE)
VALUES (SEQ_DETECTION_RULES.NEXTVAL, S.RULE_TYPE, 'EXPLICIT_SQL_SUCCESS', '외부 시스템 재전송 성공', 'EXTERNAL_INTEGRATION', 'INFO', 'Y', SYSDATE);
MERGE INTO DETECTION_RULES D USING (SELECT 'CONSTRAINT_ERROR' RULE_TYPE FROM DUAL) S
ON (D.DET_RULE_TYPE = S.RULE_TYPE)
WHEN MATCHED THEN UPDATE SET D.DET_PATTERN = 'ORA-00001|ORA-01400', D.DET_DESCRIPTION = '중복 또는 필수값 NULL 오류', D.LOG_TYPE = 'EXTERNAL_INTEGRATION', D.SEVERITY = 'ERROR'
WHEN NOT MATCHED THEN INSERT (DET_NO, DET_RULE_TYPE, DET_PATTERN, DET_DESCRIPTION, LOG_TYPE, SEVERITY, USE_YN, REG_DATE)
VALUES (SEQ_DETECTION_RULES.NEXTVAL, S.RULE_TYPE, 'ORA-00001|ORA-01400', '중복 또는 필수값 NULL 오류', 'EXTERNAL_INTEGRATION', 'ERROR', 'Y', SYSDATE);
MERGE INTO DETECTION_RULES D USING (SELECT 'BUSINESS_PROCESS_ERROR' RULE_TYPE FROM DUAL) S
ON (D.DET_RULE_TYPE = S.RULE_TYPE)
WHEN MATCHED THEN UPDATE SET D.DET_PATTERN = 'ORA-20001_AND_CLOSED', D.DET_DESCRIPTION = '일마감 처리 오류', D.LOG_TYPE = 'EXTERNAL_INTEGRATION', D.SEVERITY = 'ERROR'
WHEN NOT MATCHED THEN INSERT (DET_NO, DET_RULE_TYPE, DET_PATTERN, DET_DESCRIPTION, LOG_TYPE, SEVERITY, USE_YN, REG_DATE)
VALUES (SEQ_DETECTION_RULES.NEXTVAL, S.RULE_TYPE, 'ORA-20001_AND_CLOSED', '일마감 처리 오류', 'EXTERNAL_INTEGRATION', 'ERROR', 'Y', SYSDATE);
MERGE INTO DETECTION_RULES D USING (SELECT 'DB_TRANSFER_FAILED' RULE_TYPE FROM DUAL) S
ON (D.DET_RULE_TYPE = S.RULE_TYPE)
WHEN MATCHED THEN UPDATE SET D.DET_PATTERN = 'EXPLICIT_SQL_FAILURE', D.DET_DESCRIPTION = '외부 시스템 재전송 실패', D.LOG_TYPE = 'EXTERNAL_INTEGRATION', D.SEVERITY = 'ERROR'
WHEN NOT MATCHED THEN INSERT (DET_NO, DET_RULE_TYPE, DET_PATTERN, DET_DESCRIPTION, LOG_TYPE, SEVERITY, USE_YN, REG_DATE)
VALUES (SEQ_DETECTION_RULES.NEXTVAL, S.RULE_TYPE, 'EXPLICIT_SQL_FAILURE', '외부 시스템 재전송 실패', 'EXTERNAL_INTEGRATION', 'ERROR', 'Y', SYSDATE);
MERGE INTO DETECTION_RULES D USING (SELECT 'DB_TRANSFER_UNKNOWN' RULE_TYPE FROM DUAL) S
ON (D.DET_RULE_TYPE = S.RULE_TYPE)
WHEN MATCHED THEN UPDATE SET D.DET_PATTERN = 'NO_CONFIRMED_RESULT', D.DET_DESCRIPTION = '외부 시스템 재전송 결과 미확인', D.LOG_TYPE = 'EXTERNAL_INTEGRATION', D.SEVERITY = 'WARN'
WHEN NOT MATCHED THEN INSERT (DET_NO, DET_RULE_TYPE, DET_PATTERN, DET_DESCRIPTION, LOG_TYPE, SEVERITY, USE_YN, REG_DATE)
VALUES (SEQ_DETECTION_RULES.NEXTVAL, S.RULE_TYPE, 'NO_CONFIRMED_RESULT', '외부 시스템 재전송 결과 미확인', 'EXTERNAL_INTEGRATION', 'WARN', 'Y', SYSDATE);
MERGE INTO DETECTION_RULES D USING (SELECT 'RETRANSMISSION_SUCCESS' RULE_TYPE FROM DUAL) S
ON (D.DET_RULE_TYPE = S.RULE_TYPE)
WHEN MATCHED THEN UPDATE SET D.DET_PATTERN = 'RESPONSE_CODE_1', D.DET_DESCRIPTION = '외부 연동 정상 응답', D.LOG_TYPE = 'EXTERNAL_RETRANSMISSION', D.SEVERITY = 'INFO'
WHEN NOT MATCHED THEN INSERT (DET_NO, DET_RULE_TYPE, DET_PATTERN, DET_DESCRIPTION, LOG_TYPE, SEVERITY, USE_YN, REG_DATE)
VALUES (SEQ_DETECTION_RULES.NEXTVAL, S.RULE_TYPE, 'RESPONSE_CODE_1', '외부 연동 정상 응답', 'EXTERNAL_RETRANSMISSION', 'INFO', 'Y', SYSDATE);
MERGE INTO DETECTION_RULES D USING (SELECT 'DUPLICATE_RESPONSE' RULE_TYPE FROM DUAL) S
ON (D.DET_RULE_TYPE = S.RULE_TYPE)
WHEN MATCHED THEN UPDATE SET D.DET_PATTERN = 'KEY_DUPLICATE_ERROR', D.DET_DESCRIPTION = '외부 연동 중복 응답', D.LOG_TYPE = 'EXTERNAL_RETRANSMISSION', D.SEVERITY = 'ERROR'
WHEN NOT MATCHED THEN INSERT (DET_NO, DET_RULE_TYPE, DET_PATTERN, DET_DESCRIPTION, LOG_TYPE, SEVERITY, USE_YN, REG_DATE)
VALUES (SEQ_DETECTION_RULES.NEXTVAL, S.RULE_TYPE, 'KEY_DUPLICATE_ERROR', '외부 연동 중복 응답', 'EXTERNAL_RETRANSMISSION', 'ERROR', 'Y', SYSDATE);
MERGE INTO DETECTION_RULES D USING (SELECT 'RETRANSMISSION_FAILED' RULE_TYPE FROM DUAL) S
ON (D.DET_RULE_TYPE = S.RULE_TYPE)
WHEN MATCHED THEN UPDATE SET D.DET_PATTERN = 'NON_SUCCESS_RESPONSE', D.DET_DESCRIPTION = '외부 연동 실패 응답', D.LOG_TYPE = 'EXTERNAL_RETRANSMISSION', D.SEVERITY = 'ERROR'
WHEN NOT MATCHED THEN INSERT (DET_NO, DET_RULE_TYPE, DET_PATTERN, DET_DESCRIPTION, LOG_TYPE, SEVERITY, USE_YN, REG_DATE)
VALUES (SEQ_DETECTION_RULES.NEXTVAL, S.RULE_TYPE, 'NON_SUCCESS_RESPONSE', '외부 연동 실패 응답', 'EXTERNAL_RETRANSMISSION', 'ERROR', 'Y', SYSDATE);
MERGE INTO DETECTION_RULES D USING (SELECT 'RETRANSMISSION_UNKNOWN' RULE_TYPE FROM DUAL) S
ON (D.DET_RULE_TYPE = S.RULE_TYPE)
WHEN MATCHED THEN UPDATE SET D.DET_PATTERN = 'NO_CONFIRMED_RESPONSE', D.DET_DESCRIPTION = '외부 연동 응답 미확인', D.LOG_TYPE = 'EXTERNAL_RETRANSMISSION', D.SEVERITY = 'WARN'
WHEN NOT MATCHED THEN INSERT (DET_NO, DET_RULE_TYPE, DET_PATTERN, DET_DESCRIPTION, LOG_TYPE, SEVERITY, USE_YN, REG_DATE)
VALUES (SEQ_DETECTION_RULES.NEXTVAL, S.RULE_TYPE, 'NO_CONFIRMED_RESPONSE', '외부 연동 응답 미확인', 'EXTERNAL_RETRANSMISSION', 'WARN', 'Y', SYSDATE);
COMMIT;
