spring.application.name=logazac

#오라클 연동
spring.datasource.url=${DB_URL:jdbc:oracle:thin:@localhost:1521:xe}
spring.datasource.username=${DB_USERNAME:SYSTEM}
spring.datasource.password=${DB_PASSWORD:1234}
logazac.upload-dir=${LOGAZAC_UPLOAD_DIR:D:/doyoung/LogAzac/uploads}
logazac.python-exe=${LOGAZAC_PYTHON_EXE:python}
logazac.analyzer-path=${LOGAZAC_ANALYZER_PATH:python/analyzer.py}

# MyBatis
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# JSP
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# 파일 업로드
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
