-- ============================================================
-- LogAzac DB 초기화 스크립트
-- 대상: Oracle XE
-- 기준:
--   1) LogAzac_DB_최종_추가제약조건반영 DB 설계
--   2) 현재 MyBatis Mapper에서 실제 사용하는 컬럼/시퀀스
--   3) 관리자 규칙 등록 화면 및 Python 탐지 로직의 기본 규칙
--
-- 주의:
--   - 신규/빈 스키마에서 1회 실행하는 초기 생성용 스크립트입니다.
--   - 기존 운영 데이터가 있는 DB에는 그대로 재실행하지 마세요.
-- ============================================================

-- 1. USERS
CREATE TABLE USERS (
    USER_NO NUMBER NOT NULL,
    USER_ID VARCHAR2(20) NOT NULL,
    USER_PW VARCHAR2(100) NOT NULL,
    USER_EMAIL VARCHAR2(50) NOT NULL,
    ROLE VARCHAR2(20) DEFAULT 'USER' NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE,
    BLOCK_YN VARCHAR2(2) DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (USER_NO),
    CONSTRAINT UK_USERS_USER_ID UNIQUE (USER_ID),
    CONSTRAINT UK_USERS_USER_EMAIL UNIQUE (USER_EMAIL),
    CONSTRAINT CK_USERS_ROLE CHECK (ROLE IN ('USER', 'ADMIN')),
    CONSTRAINT CK_USERS_BLOCK_YN CHECK (BLOCK_YN IN ('Y', 'N'))
);

-- 2. LOG_FILES
CREATE TABLE LOG_FILES (
    FILE_NO NUMBER NOT NULL,
    FILE_NAME VARCHAR2(200) NOT NULL,
    FILE_SIZE NUMBER NOT NULL,
    USER_NO NUMBER NOT NULL,
    SOURCE_TYPE VARCHAR2(50) NOT NULL,
    FILE_REGDATE DATE DEFAULT SYSDATE,
    AUTO_DELETE_DATE DATE,
    FILE_PATH VARCHAR2(500) NOT NULL,
    DELETED_YN VARCHAR2(2) DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_LOG_FILES PRIMARY KEY (FILE_NO),
    CONSTRAINT FK_LOG_FILES_USER FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO),
    CONSTRAINT CK_LOG_FILES_SIZE CHECK (FILE_SIZE >= 0),
    CONSTRAINT CK_LOG_FILES_SOURCE CHECK (SOURCE_TYPE IN ('VENDING', 'PAYMENT')),
    CONSTRAINT CK_LOG_FILES_DELETED CHECK (DELETED_YN IN ('Y', 'N'))
);

-- 3. INSPECTIONS
CREATE TABLE INSPECTIONS (
    INS_NO NUMBER NOT NULL,
    FILE_NO NUMBER NOT NULL,
    INS_STATUS VARCHAR2(20) DEFAULT 'WAITING' NOT NULL,
    START_DATE DATE DEFAULT SYSDATE,
    END_DATE DATE,
    TOTAL_LINES NUMBER DEFAULT 0 NOT NULL,
    ERROR_COUNT NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT PK_INSPECTIONS PRIMARY KEY (INS_NO),
    CONSTRAINT FK_INSPECTIONS_FILE FOREIGN KEY (FILE_NO) REFERENCES LOG_FILES(FILE_NO),
    CONSTRAINT CK_INSPECTIONS_STATUS CHECK (INS_STATUS IN ('WAITING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    CONSTRAINT CK_INSPECTIONS_TOTAL CHECK (TOTAL_LINES >= 0),
    CONSTRAINT CK_INSPECTIONS_ERROR CHECK (ERROR_COUNT >= 0)
);

-- 4. DETECTION_RULES
CREATE TABLE DETECTION_RULES (
    DET_NO NUMBER NOT NULL,
    DET_RULE_TYPE VARCHAR2(200) NOT NULL,
    DET_PATTERN VARCHAR2(500) NOT NULL,
    DET_DESCRIPTION CLOB NOT NULL,
    USE_YN VARCHAR2(2) DEFAULT 'Y' NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT PK_DETECTION_RULES PRIMARY KEY (DET_NO),
    CONSTRAINT CK_DETECTION_RULES_USE CHECK (USE_YN IN ('Y', 'N'))
);

-- 5. DETECTION_RESULTS
CREATE TABLE DETECTION_RESULTS (
    RESULT_NO NUMBER NOT NULL,
    INS_NO NUMBER NOT NULL,
    DET_NO NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    LOG_CONTENT CLOB,
    DETECTED_VALUE VARCHAR2(500),
    DETECTED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT PK_DETECTION_RESULTS PRIMARY KEY (RESULT_NO),
    CONSTRAINT FK_RESULTS_INSPECTION FOREIGN KEY (INS_NO) REFERENCES INSPECTIONS(INS_NO),
    CONSTRAINT FK_RESULTS_RULE FOREIGN KEY (DET_NO) REFERENCES DETECTION_RULES(DET_NO),
    CONSTRAINT CK_RESULTS_LINE_NO CHECK (LINE_NO > 0)
);

-- 6. SEQUENCES
CREATE SEQUENCE SEQ_USERS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LOG_FILES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_INSPECTIONS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DETECTION_RULES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DETECTION_RESULTS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 7. INDEXES
-- Oracle은 FK 컬럼에 인덱스를 자동 생성하지 않으므로 별도 생성
CREATE INDEX IDX_LOG_FILES_USER_NO ON LOG_FILES(USER_NO);
CREATE INDEX IDX_LOG_FILES_SOURCE_TYPE ON LOG_FILES(SOURCE_TYPE);
CREATE INDEX IDX_INSPECTIONS_FILE_NO ON INSPECTIONS(FILE_NO);
CREATE INDEX IDX_INSPECTIONS_STATUS ON INSPECTIONS(INS_STATUS);
CREATE INDEX IDX_RESULTS_INS_NO ON DETECTION_RESULTS(INS_NO);
CREATE INDEX IDX_RESULTS_DET_NO ON DETECTION_RESULTS(DET_NO);
CREATE INDEX IDX_RESULTS_DETECTED_DATE ON DETECTION_RESULTS(DETECTED_DATE);

-- 8. 기본 이상 판단 규칙
INSERT INTO DETECTION_RULES (
    DET_NO, DET_RULE_TYPE, DET_PATTERN, DET_DESCRIPTION, USE_YN, REG_DATE
) VALUES (
    SEQ_DETECTION_RULES.NEXTVAL,
    'MISSING_PRODUCT_NAME',
    'EMPTY_PRODUCT_NAME',
    '슬롯의 상품명이 누락된 경우',
    'Y',
    SYSDATE
);

INSERT INTO DETECTION_RULES (
    DET_NO, DET_RULE_TYPE, DET_PATTERN, DET_DESCRIPTION, USE_YN, REG_DATE
) VALUES (
    SEQ_DETECTION_RULES.NEXTVAL,
    'CORRUPTED_DATA',
    'INVALID_CHARACTER',
    '로그 또는 상품명에 비정상 문자가 포함된 경우',
    'Y',
    SYSDATE
);

INSERT INTO DETECTION_RULES (
    DET_NO, DET_RULE_TYPE, DET_PATTERN, DET_DESCRIPTION, USE_YN, REG_DATE
) VALUES (
    SEQ_DETECTION_RULES.NEXTVAL,
    'MISSING_SLOT',
    'PREVIOUS_SLOT_COMPARE',
    '이전 로그에 존재하던 슬롯이 현재 로그에서 누락된 경우',
    'Y',
    SYSDATE
);

INSERT INTO DETECTION_RULES (
    DET_NO, DET_RULE_TYPE, DET_PATTERN, DET_DESCRIPTION, USE_YN, REG_DATE
) VALUES (
    SEQ_DETECTION_RULES.NEXTVAL,
    'PRICE_CHANGED',
    'PREVIOUS_PRICE_COMPARE',
    '동일 장비 동일 슬롯의 가격이 이전 값과 달라진 경우',
    'Y',
    SYSDATE
);

INSERT INTO DETECTION_RULES (
    DET_NO, DET_RULE_TYPE, DET_PATTERN, DET_DESCRIPTION, USE_YN, REG_DATE
) VALUES (
    SEQ_DETECTION_RULES.NEXTVAL,
    'PRODUCT_NAME_CHANGED',
    'PREVIOUS_NAME_COMPARE',
    '동일 장비 동일 슬롯의 상품명이 변경된 경우',
    'Y',
    SYSDATE
);

INSERT INTO DETECTION_RULES (
    DET_NO, DET_RULE_TYPE, DET_PATTERN, DET_DESCRIPTION, USE_YN, REG_DATE
) VALUES (
    SEQ_DETECTION_RULES.NEXTVAL,
    'DUPLICATE_ERROR',
    'ORA-00001',
    '무결성 제약조건 위배 오류 탐지',
    'Y',
    SYSDATE
);

INSERT INTO DETECTION_RULES (
    DET_NO, DET_RULE_TYPE, DET_PATTERN, DET_DESCRIPTION, USE_YN, REG_DATE
) VALUES (
    SEQ_DETECTION_RULES.NEXTVAL,
    'NULL_ERROR',
    'ORA-01400',
    '필수값 NULL 삽입 오류 탐지',
    'Y',
    SYSDATE
);

INSERT INTO DETECTION_RULES (
    DET_NO, DET_RULE_TYPE, DET_PATTERN, DET_DESCRIPTION, USE_YN, REG_DATE
) VALUES (
    SEQ_DETECTION_RULES.NEXTVAL,
    'CLOSED_BUSINESS_ERROR',
    'ORA-20001',
    '일마감처리된 영업장 오류 탐지',
    'Y',
    SYSDATE
);

COMMIT;

-- ============================================================
-- 관리자 계정
-- 현재 애플리케이션은 비밀번호를 BCrypt로 저장하므로 평문 비밀번호를
-- 이 초기화 SQL에 넣지 않습니다.
--
-- 1) 웹에서 일반 회원가입을 완료한 뒤
-- 2) 아래처럼 해당 계정의 ROLE만 ADMIN으로 변경하세요.
--
-- UPDATE USERS SET ROLE = 'ADMIN' WHERE USER_ID = '관리자아이디';
-- COMMIT;
-- ============================================================

-- 생성 확인용
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME IN (
    'USERS',
    'LOG_FILES',
    'INSPECTIONS',
    'DETECTION_RULES',
    'DETECTION_RESULTS'
)
ORDER BY TABLE_NAME;

SELECT DET_NO, DET_RULE_TYPE, DET_PATTERN, USE_YN
FROM DETECTION_RULES
ORDER BY DET_NO;
