-- ============================================================
-- LogAzac DB 초기화 스크립트
-- 대상: Oracle XE
-- 신규/빈 스키마에서 1회 실행하는 초기 생성용
-- 기존 데이터가 있는 DB에는 실행하지 않음
-- ============================================================

-- 1. USERS
CREATE TABLE USERS (
    USER_NO NUMBER NOT NULL,
    USER_ID VARCHAR2(20) NOT NULL,
    USER_PW VARCHAR2(100) NOT NULL,
    USER_EMAIL VARCHAR2(50) NOT NULL,
    ROLE VARCHAR2(20) DEFAULT 'USER' NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE,
    BLOCK_YN VARCHAR2(2) DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (USER_NO),
    CONSTRAINT UK_USERS_USER_ID UNIQUE (USER_ID),
    CONSTRAINT UK_USERS_USER_EMAIL UNIQUE (USER_EMAIL),
    CONSTRAINT CK_USERS_ROLE CHECK (ROLE IN ('USER', 'ADMIN')),
    CONSTRAINT CK_USERS_BLOCK_YN CHECK (BLOCK_YN IN ('Y', 'N'))
);

-- 2. LOG_FILES
CREATE TABLE LOG_FILES (
    FILE_NO NUMBER NOT NULL,
    FILE_NAME VARCHAR2(200) NOT NULL,
    FILE_SIZE NUMBER NOT NULL,
    USER_NO NUMBER NOT NULL,
    SOURCE_TYPE VARCHAR2(50) DEFAULT 'UNKNOWN' NOT NULL,
    FILE_REGDATE DATE DEFAULT SYSDATE,
    AUTO_DELETE_DATE DATE,
    FILE_PATH VARCHAR2(500) NOT NULL,
    DELETED_YN VARCHAR2(2) DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_LOG_FILES PRIMARY KEY (FILE_NO),
    CONSTRAINT FK_LOG_FILES_USER FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO),
    CONSTRAINT CK_LOG_FILES_SIZE CHECK (FILE_SIZE >= 0),
    CONSTRAINT CK_LOG_FILES_SOURCE CHECK (SOURCE_TYPE IN ('VENDING', 'PAYMENT', 'UNKNOWN', 'DEVICE_STATUS', 'EXTERNAL_RETRANSMISSION', 'EXTERNAL_INTEGRATION')),
    CONSTRAINT CK_LOG_FILES_DELETED CHECK (DELETED_YN IN ('Y', 'N'))
);

-- 3. INSPECTIONS
CREATE TABLE INSPECTIONS (
    INS_NO NUMBER NOT NULL,
    FILE_NO NUMBER NOT NULL,
    INS_STATUS VARCHAR2(20) DEFAULT 'WAITING' NOT NULL,
    START_DATE DATE DEFAULT SYSDATE,
    END_DATE DATE,
    TOTAL_LINES NUMBER DEFAULT 0 NOT NULL,
    SUCCESS_COUNT NUMBER DEFAULT 0 NOT NULL,
    SUCCESS_DEVICE_COUNT NUMBER DEFAULT 0 NOT NULL,
    FAILURE_DEVICE_COUNT NUMBER DEFAULT 0 NOT NULL,
    ERROR_COUNT NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT PK_INSPECTIONS PRIMARY KEY (INS_NO),
    CONSTRAINT FK_INSPECTIONS_FILE FOREIGN KEY (FILE_NO) REFERENCES LOG_FILES(FILE_NO),
    CONSTRAINT CK_INSPECTIONS_STATUS CHECK (INS_STATUS IN ('WAITING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    CONSTRAINT CK_INSPECTIONS_TOTAL CHECK (TOTAL_LINES >= 0),
    CONSTRAINT CK_INSPECTIONS_SUCCESS CHECK (SUCCESS_COUNT >= 0),
    CONSTRAINT CK_INSPECTIONS_SUCCESS_DEVICE CHECK (SUCCESS_DEVICE_COUNT >= 0),
    CONSTRAINT CK_INSPECTIONS_FAILURE_DEVICE CHECK (FAILURE_DEVICE_COUNT >= 0),
    CONSTRAINT CK_INSPECTIONS_ERROR CHECK (ERROR_COUNT >= 0)
);

-- 4. DETECTION_RULES
CREATE TABLE DETECTION_RULES (
    DET_NO NUMBER NOT NULL,
    DET_RULE_TYPE VARCHAR2(200) NOT NULL,
    DET_PATTERN VARCHAR2(500) NOT NULL,
    DET_DESCRIPTION CLOB NOT NULL,
    LOG_TYPE VARCHAR2(50) NOT NULL,
    SEVERITY VARCHAR2(20) DEFAULT 'ERROR' NOT NULL,
    USE_YN VARCHAR2(2) DEFAULT 'Y' NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT PK_DETECTION_RULES PRIMARY KEY (DET_NO),
    CONSTRAINT CK_DETECTION_RULES_LOG_TYPE CHECK (LOG_TYPE IN ('DEVICE_STATUS', 'EXTERNAL_RETRANSMISSION', 'EXTERNAL_INTEGRATION')),
    CONSTRAINT CK_DETECTION_RULES_SEVERITY CHECK (SEVERITY IN ('INFO', 'WARN', 'ERROR')),
    CONSTRAINT CK_DETECTION_RULES_USE CHECK (USE_YN IN ('Y', 'N'))
);

-- 5. DETECTION_RESULTS
CREATE TABLE DETECTION_RESULTS (
    RESULT_NO NUMBER NOT NULL,
    INS_NO NUMBER NOT NULL,
    DET_NO NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    DEVICE_ID VARCHAR2(100),
    SLOT_CODE VARCHAR2(50),
    RESULT_STATUS VARCHAR2(20) DEFAULT 'ERROR' NOT NULL,
    LOG_CONTENT CLOB,
    DETECTED_VALUE VARCHAR2(500),
    DETECTED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT PK_DETECTION_RESULTS PRIMARY KEY (RESULT_NO),
    CONSTRAINT FK_RESULTS_INSPECTION FOREIGN KEY (INS_NO) REFERENCES INSPECTIONS(INS_NO),
    CONSTRAINT FK_RESULTS_RULE FOREIGN KEY (DET_NO) REFERENCES DETECTION_RULES(DET_NO),
    CONSTRAINT CK_RESULTS_LINE_NO CHECK (LINE_NO > 0),
    CONSTRAINT CK_RESULTS_STATUS CHECK (RESULT_STATUS IN ('SUCCESS', 'ERROR'))
);

-- 6. SEQUENCES
CREATE SEQUENCE SEQ_USERS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LOG_FILES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_INSPECTIONS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DETECTION_RULES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DETECTION_RESULTS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 7. INDEXES
CREATE INDEX IDX_LOG_FILES_USER_NO ON LOG_FILES(USER_NO);
CREATE INDEX IDX_LOG_FILES_SOURCE_TYPE ON LOG_FILES(SOURCE_TYPE);
CREATE INDEX IDX_INSPECTIONS_FILE_NO ON INSPECTIONS(FILE_NO);
CREATE INDEX IDX_INSPECTIONS_STATUS ON INSPECTIONS(INS_STATUS);
CREATE INDEX IDX_RULES_LOG_TYPE ON DETECTION_RULES(LOG_TYPE);
CREATE INDEX IDX_RESULTS_INS_NO ON DETECTION_RESULTS(INS_NO);
CREATE INDEX IDX_RESULTS_DET_NO ON DETECTION_RESULTS(DET_NO);
CREATE INDEX IDX_RESULTS_STATUS ON DETECTION_RESULTS(RESULT_STATUS);
CREATE INDEX IDX_RESULTS_DEVICE_ID ON DETECTION_RESULTS(DEVICE_ID);
CREATE INDEX IDX_RESULTS_DETECTED_DATE ON DETECTION_RESULTS(DETECTED_DATE);

-- 8. DEVICE_STATUS 기본 규칙
INSERT INTO DETECTION_RULES VALUES (SEQ_DETECTION_RULES.NEXTVAL, 'MISSING_PRODUCT_NAME', 'EMPTY_PRODUCT_NAME', '슬롯의 상품명이 누락된 경우', 'DEVICE_STATUS', 'ERROR', 'Y', SYSDATE);
INSERT INTO DETECTION_RULES VALUES (SEQ_DETECTION_RULES.NEXTVAL, 'CORRUPTED_DATA', 'INVALID_CHARACTER', '로그 또는 상품명에 비정상 문자가 포함된 경우', 'DEVICE_STATUS', 'ERROR', 'Y', SYSDATE);
INSERT INTO DETECTION_RULES VALUES (SEQ_DETECTION_RULES.NEXTVAL, 'MISSING_SLOT', 'PREVIOUS_SLOT_COMPARE', '이전 로그에 존재하던 슬롯이 현재 로그에서 누락된 경우', 'DEVICE_STATUS', 'ERROR', 'Y', SYSDATE);
INSERT INTO DETECTION_RULES VALUES (SEQ_DETECTION_RULES.NEXTVAL, 'PRICE_CHANGED', 'PREVIOUS_PRICE_COMPARE', '동일 장비 동일 슬롯의 가격이 이전 값과 달라진 경우', 'DEVICE_STATUS', 'ERROR', 'Y', SYSDATE);
INSERT INTO DETECTION_RULES VALUES (SEQ_DETECTION_RULES.NEXTVAL, 'PRODUCT_NAME_CHANGED', 'PREVIOUS_NAME_COMPARE', '동일 장비 동일 슬롯의 상품명이 변경된 경우', 'DEVICE_STATUS', 'ERROR', 'Y', SYSDATE);

-- 9. EXTERNAL_RETRANSMISSION 기본 규칙
INSERT INTO DETECTION_RULES VALUES (SEQ_DETECTION_RULES.NEXTVAL, 'RETRANSMISSION_SUCCESS', 'RESPONSE_CODE_1', '외부 시스템 재전송이 정상 처리된 경우', 'EXTERNAL_RETRANSMISSION', 'INFO', 'Y', SYSDATE);
INSERT INTO DETECTION_RULES VALUES (SEQ_DETECTION_RULES.NEXTVAL, 'DUPLICATE_RESPONSE', 'KEY_DUPLICATE_ERROR', '외부 시스템 재전송에서 중복 응답이 발생한 경우', 'EXTERNAL_RETRANSMISSION', 'ERROR', 'Y', SYSDATE);
INSERT INTO DETECTION_RULES VALUES (SEQ_DETECTION_RULES.NEXTVAL, 'RETRANSMISSION_FAILED', 'NON_SUCCESS_RESPONSE', '외부 시스템 재전송이 정상 완료되지 않은 경우', 'EXTERNAL_RETRANSMISSION', 'ERROR', 'Y', SYSDATE);

-- 10. EXTERNAL_INTEGRATION 기본 규칙
INSERT INTO DETECTION_RULES VALUES (SEQ_DETECTION_RULES.NEXTVAL, 'DB_TRANSFER_SUCCESS', 'COMPLETED_WITHOUT_ERROR', 'DB 재전송 작업이 오류 없이 정상 진행된 경우', 'EXTERNAL_INTEGRATION', 'INFO', 'Y', SYSDATE);
INSERT INTO DETECTION_RULES VALUES (SEQ_DETECTION_RULES.NEXTVAL, 'CONSTRAINT_ERROR', 'ORA-00001|ORA-01400', 'DB 재전송 중 중복 데이터 또는 필수값 누락 오류가 발생한 경우', 'EXTERNAL_INTEGRATION', 'ERROR', 'Y', SYSDATE);
INSERT INTO DETECTION_RULES VALUES (SEQ_DETECTION_RULES.NEXTVAL, 'BUSINESS_PROCESS_ERROR', 'ORA-20001', 'DB 재전송 중 업무 처리 조건에 의해 거부된 경우', 'EXTERNAL_INTEGRATION', 'ERROR', 'Y', SYSDATE);
INSERT INTO DETECTION_RULES VALUES (SEQ_DETECTION_RULES.NEXTVAL, 'DB_TRANSFER_FAILED', 'DB_TRANSFER_ERROR', 'DB 재전송 작업이 정상 완료되지 않은 경우', 'EXTERNAL_INTEGRATION', 'ERROR', 'Y', SYSDATE);

COMMIT;

-- 관리자 계정은 회원가입 후 ROLE 변경
-- UPDATE USERS SET ROLE = 'ADMIN' WHERE USER_ID = 'admin';
-- COMMIT;

-- 생성 확인
SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME IN ('USERS', 'LOG_FILES', 'INSPECTIONS', 'DETECTION_RULES', 'DETECTION_RESULTS') ORDER BY TABLE_NAME;
SELECT DET_NO, LOG_TYPE, DET_RULE_TYPE, SEVERITY, USE_YN FROM DETECTION_RULES ORDER BY DET_NO;