name: Deploy LogAzac
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy LogAzac
        run: |
          cd /home/dy8327/LogAzac
          git pull origin master
          chmod +x mvnw
          ./mvnw clean package -DskipTests
          sudo /usr/bin/systemctl restart logazac
          /usr/bin/systemctl is-active logazac
